### ISSUE TITLE
Credentials filename is not windows compatible

### ISSUE THREAD

**Issue by luck428** [tomasbedrich/pycaching#112]
The filename for the gc credentials is not windows compatible (at least WIN XP)
#   _credentials_file = ".gc_credentials"
    _credentials_file = "gc_credentials.txt"

If changed (mostly the point at the beginning) then the login works.

**Comment by weinshec** [comment]
Hi @luck428 

I'm not a Windows guy, but from what I found it seems very WinXP-specific to me - Windows Explorer in particular. Have you tried "creating" the file using an editor, e.g. Notepad, using the "Save As..." Dialog with filetype "All Files" selected?

Unfortunately, I don't have a WinXP machine available in order to test this.

**Comment by FriedrichFroebel** [comment]
As far as I remember, creating files without any text before the text (the filename part) still leads to an error in Windows 8 saying something like "The filename cannot be empty." (Not observed for this specific case, but when creating `.gitignore` files.)

**Comment by luck428** [comment]
Weinshec is right. If the file is created directly out of microsoft explorer, the comma at the beginning will be invalid. Hoewever if the file iscreated from notepad with saveas the comma is allowed and the file can be stored. So there is a workaround and the issue is a watchout for windows users.
