### ISSUE TITLE
Retrieve the number of founds/visits of a cache

### ISSUE THREAD

**Issue by Gebruikertje** [tomasbedrich/pycaching#128]
Is it possibility to add the functionality to retrieve the number of founds of cache, just like retrieving the number of favorites?

Regards, Peter

**Comment by tomasbedrich** [comment]
Thanks for a suggestion. Currently I don't have time to work on this, but as discussed in email previously:
> it shouldn't be difficult to add that functionality because the number of found caches is on each page in the header.
So if any contributor (or you) would like to take care of this, it would be welcome.

**Comment by FriedrichFroebel** [comment]
The statement regarding the header seems to be wrong, as this feature request is about the log count from the logbook of the corresponding cache instead of the log count by the currently logged in user.

It seems like the needed data can be retrieved from the cache details page using the following block:

    <span id="ctl00_ContentBody_lblFindCounts"><p class="LogTotals">

Inside it, the different log types seem to be enumerated using an image and the count in alternating order.

We may add a `log_count` dictionary to the `Cache` class for this using the `log.Type` as the key and the corresponding count as the value. This way we do not restrict this to the founds, but provide other log type counts as well.

**Comment by tomasbedrich** [comment]
Thanks for correcting me! I like your implementation idea, looking forward to see a PR. :)
