### ISSUE TITLE
Feature proposal: create or edit notifications

### ISSUE THREAD

**Issue by mrummuka** [tomasbedrich/pycaching#85]
Hi,
I'd like to know if it was reasonably possible to add support for creating (or simply editing existing) notifications. My personal need/ use case consists updating coordinates of FTF notifications whenever I change my location and I've done some experimentation how to make this straight forward by using additional tools.

**Comment by tomasbedrich** [comment]
Hi, although it sounds like a nice idea, I think it is not something that should be in the pycaching core. The first reason is, that it is only a premium member feature and the second reason is, that it is highly specific thing to do with Geocaching website, but pycaching aims to be more a general interface for objects like Caches, Logs or Trackables.

I would recommend you to create a fork (or another python module), which could use a [Geocaching._request method](https://github.com/tomasbedrich/pycaching/blob/master/pycaching/geocaching.py#L39). This will provide you a possibility to share login logic with pycaching. Then you can use it the same way as Cache or Trackable does ([example](https://github.com/tomasbedrich/pycaching/blob/master/pycaching/cache.py#L874)). Of course, this is a bit dangerous, because it is internal API, but I don't think that it will change in near future.
